#!/bin/sh

# PROVIDE: Number42
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# Number42_enable (bool): Set to NO by default. Set this variable to YES if you want to enable Number42 service.
# Number42_config (path): Set to /usr/local/etc/Number42.conf by default.
# Number42_user:  The user account Number42 daemon runs as. It uses 'root' user by default.
# Number42_group: The group account Number42 daemon runs as. It uses 'wheel' group by default.
# Number42_datadir (str): Default to "/var/db/Number42". Base data directory.

. /etc/rc.subr

name=Number42
rcvar=Number42_enable

: ${Number42_enable:=NO}
: ${Number42_config=/usr/local/etc/Number42.conf}
: ${Number42_datadir=/var/db/Number42}
: ${Number42_user="root"}
: ${Number42_group="wheel"}

required_files=${Number42_config}
command=/usr/local/bin/Number42d
Number42_chdir=${Number42_datadir}
pidfile="${Number42_datadir}/Number42d.pid"
stop_cmd=Number42_stop
command_args="-conf=${Number42_config} -datadir=${Number42_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

Number42_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${Number42_datadir}
	[ $? -eq 0 ] && chown -R ${Number42_user}:${Number42_group} ${Number42_datadir}
}

Number42_prestart()
{
	if [ ! -d "${Number42_datadir}/." ]; then
		Number42_create_datadir || return 1
	fi
}

Number42_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

Number42_stop()
{
    Number42_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${Number42_config} -datadir=${Number42_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
